"""State definitions for DevOps Engineer Multi-Agent System.

This module defines the state structure and enums for coordinating
DevOps workflow orchestration across specialized subagents.
"""

from enum import Enum
from typing import Annotated, Any, Dict, List, TypedDict

from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


class DevOpsTaskType(Enum):
    """Enumeration of DevOps task types."""

    DEPLOY = "deploy"
    MONITOR = "monitor"
    DEBUG = "debug"
    PROVISION = "provision"
    OPTIMIZE = "optimize"
    INCIDENT_RESPONSE = "incident_response"
    SECURITY_AUDIT = "security_audit"


class DevOpsAgentState(TypedDict):
    """State for the DevOps Engineer Multi-Agent System.

    Attributes:
        messages: Conversation history with automatic message merging
        task_type: The type of DevOps task being executed
        context: Additional task context and metadata
        current_phase: Current workflow phase/stage

        # Routing
        supervisor_path: Ordered supervisors that handled routing
        routing_trace: Routing decisions made by supervisors
        next_action: Next action to take in the workflow

        # Agent results
        subagent_results: Results collected from each subagent
        active_agents: List of currently active agents

        # Infrastructure context
        infrastructure_state: Current infrastructure state (pods, services, deployments)
        metrics: Monitoring metrics and performance data
        logs: Collected log entries from various sources
        alerts: Active alerts and notifications

        # Knowledge retrieval
        retrieved_docs: Documents retrieved from Pinecone knowledge base
        search_queries: Queries made to the knowledge base

        # Tool results
        web_search_results: Results from web search operations
        api_responses: Responses from custom API calls

        # Memory and reflection
        memory_bus: Shared memory bus reference for workflow data
        reflection_outcomes: Assessment of subagent outputs
        remediation_tasks: Follow-up tasks generated by reflection
    """

    # Core workflow
    messages: Annotated[List[BaseMessage], add_messages]
    task_type: str
    context: Dict[str, Any]
    current_phase: str

    # Routing
    supervisor_path: List[str]
    routing_trace: List[Dict[str, str]]
    next_action: str

    # Agent results
    subagent_results: Dict[str, Any]
    active_agents: List[str]

    # Infrastructure context
    infrastructure_state: Dict[str, Any]
    metrics: Dict[str, Any]
    logs: List[Dict[str, Any]]
    alerts: List[Dict[str, Any]]

    # Knowledge retrieval
    retrieved_docs: List[Dict[str, Any]]
    search_queries: List[str]

    # Tool results
    web_search_results: List[Dict[str, Any]]
    api_responses: Dict[str, Any]

    # Memory and reflection
    memory_bus: Any
    reflection_outcomes: Dict[str, Any]
    remediation_tasks: List[Dict[str, Any]]
